# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# experimental - you can use 'mic' to control your mic input level (uses the default recording device)
# windows only - you can use 'system' to control the "system sounds" volume
slider_mapping:
  0: master
  1: system
  2: wow.exe
  3:
    - twitchui.exe
    - chrome.exe
  4: discord.exe

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM3
baud_rate: 9600

# limits how often deej will look for new processes
# it's recommended to leave this setting at its default value
process_refresh_frequency: 1
